vo_mode: "mono" #mono or stereo

# Topic Names
left_camera_topic: "/camera/left/image_raw"
right_camera_topic: "/camera/right/image_raw" # Ignored if mode is mono

# Paths to Sensor Calibration Files
left_camera_config_path: "/path/to/config/left_camera.yaml"
right_camera_config_path: "/path/to/config/right_camera.yaml"
imu_config_path: "/path/to/config/imu.yaml"